id = "jsonx"
name = "JSONx"
version = "0.0.1"
schema_version = 1
authors = ["Shanhu <dev@shanhu.io>"]
description = "Syntax highlighting for JSONx, a JSON dialect (shanhu.io/std/jsonx)."
repository = "https://github.com/shanhuio/std"

[grammars.jsonx]
repository = "https://github.com/shanhuio/tree-sitter-jsonx"
commit = "87e2858a7e2339c755cbf2830df400ce610e0a85"
