id = "jsonx"
name = "JSONx"
version = "0.2.0"
schema_version = 1
authors = ["Shanhu Tech Inc. <contact@shanhu.io>"]
description = "Syntax highlighting for JSONx, a JSON dialect (shanhu.io/std/jsonx)."
repository = "https://github.com/shanhuio/std"

[grammars.jsonx]
repository = "https://github.com/shanhuio/tree-sitter-jsonx"
commit = "da192e035918acd386299ea9a31ac104a7fef87b"
