id = "jsonx"
name = "JSONx"
version = "0.0.1"
schema_version = 1
authors = ["Shanhu <dev@shanhu.io>"]
description = "Syntax highlighting for JSONx, a JSON dialect (shanhu.io/std/jsonx)."
repository = "https://github.com/shanhuio/std"

[grammars.jsonx]
repository = "https://github.com/shanhuio/tree-sitter-jsonx"
commit = "b2f0c831814ebfcb4bb20e1a00f62621e9865f3d"
